our = data;
for k=1:m
   our(k,2)=data(k,2)-nei(k,2);
end;

figure;
hold on;
plot(our(:,1),our(:,2),'ro','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','g',...
                'MarkerSize',6);
plot(our(1,1),our(1,2),'ro','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','r',...
                'MarkerSize',6);
plot(our(m,1),our(m,2),'ro','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','r',...
                'MarkerSize',6);

title('Outliers Detected Using Spatial Test','fontsize',22);
xlabel('Location','fontsize',20);
ylabel('Statistical Test S(x)','fontsize',20);
text(4.8,3.4,'S \rightarrow','FontSize',14);
hold off;
%print -djpeg90 our3.jpg

