%% 对得到的数据进行聚类分析
function [num,h,nodes]=clu(num)
eucD = pdist(num,'euclidean');
clustTreeEuc = linkage(eucD,'average');
cophenet(clustTreeEuc,eucD);
P3 = figure;clf;
[h,nodes] =  dendrogram(clustTreeEuc,40);
set(gca,'TickDir','out','TickLength',[.002 0],'XTickLabel',[]);
set(gca,'XTickLabel',{'年生产总值';'人均GDP';'规模以上工业总产值';...
    '全市财政收入';...
    '社会固定资产投资';'社会消费品零售总额';'进出口总额';...
    '公共预算总收入';...
    '城镇人均可支配收入';'农村人均可支配收入';...
    '卫生医疗机构（个）';'第一产业占比';...
    '第二产业占比';'第三产业占比'});
axis([1 11 0 5000]);
% axis([1 14 0 170000])